### ISSUE TITLE
cell c rtl31vw and cell c rtl30vw

### ISSUE THREAD

**Issue by Mvp55555** [sartura/openwrt#20]
hi everyone 
i am new on this website 

i have cell c rtl31vw and cell c rtl30vw routers 
but it's not showing option to use with simcard it's only giving me option for ethernet not LTE

please guys if anyone can help me and show me how to do it also 

please please please

thank you

**Comment by jmv2009** [comment]
Yeah... Sartura/openwrt is for developing openwrt, and even some sub-development thereof. Openwrt may or may not have support for these routers. Are you even running openwrt, or just using stock firmware? In any case, you should almost certainly be somewhere else for basically end-support. (And sorry to point out that your broken English does not appear to help either)
